# For console output
# output: console
# level: info

# For file output
# output: file
# level: info
# file_path: "logs"
# file_name: "app.log"

output: grpc
level: info
grpc:
  address: "127.0.0.1"
  port: 50051
